Feature/crud users mensajes
Open-Bootcamp/protectoras-animales pull request #105
Opened 2022-08-28 14:47 UTC by KussFrSo

2022-08-28 17:14 UTC, KussFrSo commented
Aun no hagáis el Merge, tengo que revisar un par de cosas que me ha comentado Camper

2022-08-29 16:50 UTC, KussFrSo commented
Aun no hagáis el merge me falta el ultimo check que tenia dudas

2022-08-30 13:05 UTC, pedrovelasquez9 commented
@KussFrSo has podido resolver las dudas o no hacemos merge todavía?

2022-08-30 14:16 UTC, KussFrSo commented
@pedrovelasquez9 Si! Era la duda que te pregunte ayer en la tutoría. Gracias!

2022-08-30 14:17 UTC, pedrovelasquez9 commented
@KussFrSo perfect, hago el merge entonces o te falta algo?

2022-08-30 14:58 UTC, KussFrSo commented
@pedrovelasquez9 aun no, que me falta acabar de hacer el ultimo check de la issue: 
"Agregar endpoint adicional para consultar conversaciones que un usuario en particular haya tenido con otros usuarios de la plataforma"
Cuando lo tenga echo os enviare un mensaje por aquí (en la PR) con el @ indicando que ya podéis hacer merge. 
Gracias!

2022-08-30 15:04 UTC, pedrovelasquez9 commented
@KussFrSo Perfect, la marco como que necesita cambio para que nadie haga el merge por accidente =)

2022-08-30 15:04 UTC, pedrovelasquez9 requested changes
A la espera de cambios identificados para terminar las sub tareas

2022-08-30 18:24 UTC, KussFrSo commented
@pedrovelasquez9 ya esta todo listo, ya puedes hacer el merge. Gracias!

2022-08-31 07:03 UTC, AMDevelopOB approved these changes
Buen trabajo con la gestión de mensajes, así a priori parece correcto usar lucid como un sistema de almacenamiento de mensajes, pero deberemos tener en cuenta los tiempos de carga, ya que si existen registrados 10000 mensajes la consulta a la base de datos puede tener una carga tardía. 

Por otro lado, en cuanto al archivo de rutas Adonis permite simplificarlo con el método apiOnly(), de manera que no debes especificar ruta por ruta el controlador asociado, si no que son autogestionados por el framework.
https://docs.adonisjs.com/guides/controllers#api-only-routes

Buen trabajo!

2022-08-31 07:03 UTC, merged